name: Node CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 12.x]
    
    name: Use Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          curl https://install.meteor.com/ | sh
          npm install --production
          mkdir build
          npm meteor build ./build --architecture os.linux.x86_64
        env:
          CI: true
